query GetDisasters(
  $orderBy: disasterDescriptive_orderBy!
  $orderDirection: OrderDirection!
) {
  disasters {
    id
    transactionHash
    totalFundingAmount
  }
  disasterDescriptives(orderBy: $orderBy, orderDirection: $orderDirection) {
    id
    name
    description
    disasterType
    location
    createdAt
    fundsNeeded
    attestationId
    hyperlaneMessageId
    transactionHash
  }
}
